# Generated by Django 3.2.6 on 2021-08-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardAnalysis', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='First Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='Last Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passw',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uname',
            new_name='Username',
        ),
    ]
