# Generated by Django 3.2.6 on 2021-09-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardAnalysis', '0004_auto_20210807_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siximage',
            name='image1',
            field=models.ImageField(upload_to='<username>/'),
        ),
        migrations.AlterField(
            model_name='siximage',
            name='image2',
            field=models.ImageField(upload_to='<username>/'),
        ),
        migrations.AlterField(
            model_name='siximage',
            name='image3',
            field=models.ImageField(upload_to='<username>/'),
        ),
        migrations.AlterField(
            model_name='siximage',
            name='image4',
            field=models.ImageField(upload_to='<username>/'),
        ),
        migrations.AlterField(
            model_name='siximage',
            name='image5',
            field=models.ImageField(upload_to='<username>/'),
        ),
        migrations.AlterField(
            model_name='siximage',
            name='image6',
            field=models.ImageField(upload_to='<username>/'),
        ),
    ]
