# Generated by Django 3.2.6 on 2021-09-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardAnalysis', '0005_auto_20210912_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siximage',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='siximage',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='siximage',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='siximage',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='siximage',
            name='image5',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='siximage',
            name='image6',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
